name: SMT Synth

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        compiler: [ # { ghc: '8.10.7', cabal: '3.10' },
                    # { ghc: '9.0.2', cabal: '3.10' },
                    # { ghc: '9.2.4', cabal: '3.10' },
                    # { ghc: '9.4.4', cabal: '3.10' },
                    # { ghc: '9.6.1', cabal: '3.10' },
                    # { ghc: '9.8.4', cabal: '3.10' },
                    # { ghc: '9.10.3', cabal: '3.10' },
                    { ghc: '9.12.2', cabal: '3.12' } ]
    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.compiler.ghc }}
        cabal-version: ${{ matrix.compiler.cabal }}

    - run: cabal update
    - run: cabal configure --enable-tests -f -support-lh
    - run: cabal freeze
    # - uses: actions/cache@v3
    #   with:
    #     path: |
    #       ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
    #       dist-newstyle
    #     key: cabal-${{ runner.os }}-${{ matrix.compiler.ghc }}-${{ hashFiles('cabal.project.freeze') }}
    #     restore-keys: |
    #       cabal-${{ runner.os }}-${{ matrix.compiler.ghc }}-

    - name: Install CVC5
      run: sudo apt-get install cvc5
   
    - name: Getting custom base
      run: bash base_setup.sh

    - name: Install dependencies
      run: |
        cabal install --only-dependencies
    - name: Build
      run: cabal build G2
    # - name: Run tests
    #   run: cabal run test-nebula-plugin